#!/usr/bin/env bash

iDIR="$HOME/.config/mako/icons"

# Get Volume
get_volume() {
    volume=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2 * 100}')
    echo "$volume"
}

# Increase Volume
inc_volume() {
    if [[ "$(get_volume)" -ge "100" ]]; then
        wpctl set-volume @DEFAULT_SINK@ 1
    else
        wpctl set-volume @DEFAULT_SINK@ 0.02+
    fi
    notify_user
}

# Decrease Volume
dec_volume() {
    wpctl set-volume @DEFAULT_SINK@ 0.02- && notify_user
}

# Notify
notify_user() {
    notify-send -c volume -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" -h "int:value:$(get_volume)" " "
}

# Get icons
get_icon() {
    current=$(get_volume)
    if [[ "$current" -eq "0" ]]; then
        echo "$iDIR/volume-mute.png"
    elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
        echo "$iDIR/volume-low.png"
    elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
        echo "$iDIR/volume-mid.png"
    elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
        echo "$iDIR/volume-high.png"
    fi
}

# Toggle Mute
toggle_mute() {
    wpctl set-mute @DEFAULT_SINK@ toggle
    if [ "$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $3}')" == "[MUTED]" ]; then
        notify-send -c volume -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
    elif [ "$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $3}')" == "" ]; then
        notify-send -c volume -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
    fi
}

# Get Mic Volume
#get_mic_volume() {
#    volume=$(wpctl get-volume @DEFAULT_SOURCE@ | awk '{print $2 * 100}')
#    echo "$volume"
#}

# Toggle Mic
#toggle_mic() {
#    wpctl set-mute @DEFAULT_SOURCE@ toggle
#    if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
#        notify-send -c volume -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
#    elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
#        notify-send -c volume -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
#    fi
#}

# Get icons
#get_mic_icon() {
#    current=$(get_mic_volume)
#    if [[ "$current" -eq "0" ]]; then
#        echo "$iDIR/microphone.png"
#    elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
#        echo "$iDIR/microphone.png"
#    elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
#        echo "$iDIR/microphone.png"
#    elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
#        echo "$iDIR/microphone.png"
#    fi
#}

# Notify
#notify_mic_user() {
#    notify-send -c volume -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Mic-Level : $(pamixer --default-source --get-volume) %"
#}

# Increase MIC Volume
#inc_mic_volume() {
#    pamixer --default-source -i 5 && notify_mic_user
#}

# Decrease MIC Volume
#dec_mic_volume() {
#    pamixer --default-source -d 5 && notify_mic_user
#}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
    toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
    get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
    get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
    inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
    dec_mic_volume
else
    get_volume
fi
